version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_AUTH_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_AUTH_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
volumes:
  mongodb_data:
