name: Push build to branch

on:
  pull_request:
    branches: ['main']
    types: ['closed']

  workflow_dispatch:

env:
  APP_NAME: gs-backend

jobs:
  build:
    name: Create build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Building application
        run: npm run build

      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build 
          FOLDER: dist 
          MESSAGE: "Build: ({sha}) {msg}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
