name: Pre-merge Checks

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  eslint:
    name: Validate with ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Install ESLint
        run: |
          npm install eslint@latest
          npm install @microsoft/eslint-formatter-sarif@latest

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .ts,.js,.tsx,.jsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  node:
    name: Install NodeJS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Installing NodeJS v${{ matrix.node-version }}...
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing dependencies...
        run: npm ci

  test:
    name: Pass unit-tests with Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checking code...
        uses: actions/checkout@v3

      - name: Running tests...
        run: npm run test

  build:
    name: Generate builds
    runs-on: ubuntu-latest

    steps:
      - name: Installing dependencies...
        run: npm ci

      - name: Building...
        run: npm run build

      - name: Start test flight...
        run: npm run start:prod
