name: Pre-prequest

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

env:
  APP_NAME: gs-backend

jobs:
  codebase:
    name: Code base Check
    runs-on: ubuntu-latest

    steps:
      - name: Check code base
        uses: actions/checkout@v3

  eslint:
    name: ESLint validations
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Install ESLint
        run: |
          npm install eslint@latest
          npm install @microsoft/eslint-formatter-sarif@latest

      - name: Run lint
        run: npx eslint .
          --config .eslintrc.js
          --ext .ts,.js,.tsx,.jsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Create lint report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  test:
    name: Jest unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Install NodeJS 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Create build
        run: npm run build

  docker:
    name: Docker image test
    runs-on: ubuntu-latest

    steps:
      - name: Creating '.env' file
        shell: bash
        env:
          ENV: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV" > .env

      - name: Docker test build image 
        run: docker build . --no-cache -t $APP_NAME

      - name: Docker drop test image
        run: docker rmi $APP_NAME
