name: Push build to production branch

on:
  pull_request:
    branches: ['main']
    types: ['closed']

  workflow_dispatch:

env:
  APP_NAME: gs-backend

jobs:
  validate:
    name: Push build to production branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Check code base
        uses: actions/checkout@v3

      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prepare ESLint
        run: |
          npm install eslint@latest
          npm install @microsoft/eslint-formatter-sarif@latest

      - name: Run lint
        run: npx eslint .
          --config .eslintrc.js
          --ext .ts,.js,.tsx,.jsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload ESLint Analysis
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Running tests
        run: npm run test

      - name: Create app build
        run: npm run build

      - name: Docker test image
        run: docker build . --no-cache -t $APP_NAME

      - name: Docker delete image
        run: docker rmi $APP_NAME

      - name: Push from dev to prod branch.
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'production'
          commit_message: 'Tested, lined and auto-merged with Production'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required

